// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxfpREcSLwxjOcdinp-aYvsHFlIChNXec',
    appId: '1:344927444374:web:e68763f96111d6185851b7',
    messagingSenderId: '344927444374',
    projectId: 'people-management-tool',
    authDomain: 'people-management-tool.firebaseapp.com',
    storageBucket: 'people-management-tool.firebasestorage.app',
    measurementId: 'G-Z86PRP0V5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_az1jQ9sgnMAhUDOXvQPks9W5nWZNRfM',
    appId: '1:344927444374:android:cc1ccd45f6a5050f5851b7',
    messagingSenderId: '344927444374',
    projectId: 'people-management-tool',
    storageBucket: 'people-management-tool.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzv2NOA3Fpdsdix_xKXUm2Jq7SZlhZW9c',
    appId: '1:344927444374:ios:7e3da8885b305a665851b7',
    messagingSenderId: '344927444374',
    projectId: 'people-management-tool',
    storageBucket: 'people-management-tool.firebasestorage.app',
    iosBundleId: 'com.tanvijadhav.sowaka',
  );
}
